export type { IMAP } from './class/IMAP.js'
export type { SimplexIMAP } from './class/SimplexIMAP.js'
export type { IMAPCredentials, IMAPConfig, TLSOptions } from './config/defaultConfig.js'
export type { IMAPResponseLine } from './model/IMAPResult.js'
export type { IMAPState } from './model/IMAPState.js'
