name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: enable pnpm
        run: corepack enable

      - name: install deps
        run: pnpm install

      - name: build lib
        run: pnpm build

      - name: setup git config
        run: |
          git config --global user.email "foxhable@gmail.com"
          git config --global user.name "foxhable"

      - name: change version of package
        run: npm version ${{ github.event.release.tag_name }}

      - name: push version commits
        run: |
          git show
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "${{ github.head_ref }}"

      - name: publish beta
        if: ${{ github.event.release.is_prerelease }}
        run: npm publish --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish latest
        if: ${{ !github.event.release.is_prerelease }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
