name: Publish

on:
  release:
    types: [published]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: setup git config
        run: |
          git config --global user.email "github-actions@github.com>"
          git config --global user.name "github-actions"

      - name: enable pnpm
        run: corepack enable

      - name: set .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc

      - name: install deps
        run: pnpm install

      - name: build lib
        run: pnpm build

      - name: set beta version
        if: ${{ github.event.release.prerelease }}
        run: npm version --git-tag-version=false ${{ github.event.release.tag_name }}

      - name: set stable version
        if: ${{ !github.event.release.prerelease }}
        run: npm version ${{ github.event.release.tag_name }} -m "v%s" | git push

      - name: publish beta
        if: ${{ github.event.release.prerelease }}
        run: npm publish --tag=beta

      - name: publish latest
        if: ${{ !github.event.release.prerelease }}
        run: npm publish
