name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@foxhable'

      - name: enable pnpm
        run: corepack enable

      - name: install deps
        run: pnpm install

      - name: build lib
        run: pnpm build

      - name: publish beta
        if: ${{ github.event.release.prerelease }}
        run: npm publish --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish latest
        if: ${{ !github.event.release.prerelease }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
